# NumPy Start


In [1]:
import numpy as np
x = np.array([1,2,3,4,5])


In [2]:
print(x)

[1 2 3 4 5]


In [3]:
x = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]], np.int16)

In [4]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
print(x[:,3])

[4 9]


In [6]:
print(x[:,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
print(x[1,:])

[ 6  7  8  9 10]


# 3D array

In [8]:
x = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]], np.int16)

In [9]:
print(x)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [10]:
print(type(x))

<class 'numpy.ndarray'>


In [11]:
print(x[0,1,3])

9


In [12]:
print(x[:,:,3])

[[ 4  9]
 [14 19]]


In [13]:
print(x[:,0,3])

[ 4 14]


In [14]:
print(x[:,1,3])

[ 9 19]


# Ndarray Properties


In [15]:
x = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],[[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]], np.int16)
print(x)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [16]:
print(x.shape)   # Shape of an Array
print(x.ndim)    # Dimension of an Array 
print(x.size)
print(x.dtype)
print(x.nbytes)

(2, 2, 5)
3
20
int16
40


In [17]:
print(x.T)     # Transpose of an Array

[[[ 1 11]
  [ 6 16]]

 [[ 2 12]
  [ 7 17]]

 [[ 3 13]
  [ 8 18]]

 [[ 4 14]
  [ 9 19]]

 [[ 5 15]
  [10 20]]]


# NumPy Constants

In [18]:
print(np.inf)    # Positive Infinity
print(np.NINF)   # Negative Infinity
print(np.NAN)    # Not A Number
print(np.PZERO)  # Positive Zero
print(np.NZERO)  # Negative Zero

inf
-inf
nan
0.0
-0.0


In [19]:
print(np.e)
print(np.euler_gamma)
print(np.pi)

2.718281828459045
0.5772156649015329
3.141592653589793
