In [2]:
import numpy as np

# x = np.empty([3, 3], np.uint16)
x = np.empty([3, 3], np.uint8)
print(x)

[[128  47 147]
 [ 26 196 127]
 [  0   0  24]]


In [19]:
y = np.eye(5)
print(y)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
y = np.eye(5, dtype=np.uint8)
print(y)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [6]:
y = np.eye(5, dtype=np.uint8, k=1)
print(y)

[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [7]:
y = np.eye(5, dtype=np.uint8, k=-1)
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


In [8]:
y = np.eye(5, dtype=np.uint16, k=2)
print(y)

[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [9]:
y = np.identity(5, dtype = np.uint8)
print(y)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [13]:
y = np.zeros([2,5,5], dtype = np.uint8)
print(y)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [14]:
y = np.ones([3, 4, 5], dtype = np.uint8)
print(y)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [16]:
y = np.full([3, 4, 6], dtype = np.uint8, fill_value = 10)
print(y)

[[[10 10 10 10 10 10]
  [10 10 10 10 10 10]
  [10 10 10 10 10 10]
  [10 10 10 10 10 10]]

 [[10 10 10 10 10 10]
  [10 10 10 10 10 10]
  [10 10 10 10 10 10]
  [10 10 10 10 10 10]]

 [[10 10 10 10 10 10]
  [10 10 10 10 10 10]
  [10 10 10 10 10 10]
  [10 10 10 10 10 10]]]


In [3]:
x = np.tri(5, 5, k=1, dtype=np.uint16)
print(x)

[[1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [4]:
x = np.ones((5, 5), dtype=np.uint16)
y = np.tril(x, k=-1)
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [5]:
x = np.ones((5, 5), dtype = np.uint16)
y = np.tril(x, k = -2)
print(y)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]]


In [6]:
x = np.ones((5, 5), dtype = np.uint16)
y = np.triu(x, k=0)
print(y)

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]


In [7]:
x = np.ones((5, 5), dtype = np.uint16)
y = np.triu(x, k=3)
print(y)

[[0 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
