In [1]:
import numpy as np


In [2]:
x = np.random.randint(low = 0, high = 9, size = 10)
print(x)

[0 1 5 1 4 4 7 6 3 4]


In [3]:
x = np.random.rand(3, 3)
print(x)

[[0.08948005 0.41135521 0.64080131]
 [0.64136518 0.27738266 0.4903896 ]
 [0.3955362  0.85817323 0.07851076]]


In [4]:
x = np.random.rand(2, 2, 2, 2, 2)
print(x)

[[[[[0.33257738 0.89419062]
    [0.54981186 0.45455702]]

   [[0.98723832 0.58055471]
    [0.01062309 0.79443849]]]


  [[[0.1262875  0.27520426]
    [0.27001373 0.68131742]]

   [[0.91940533 0.64156331]
    [0.22550494 0.2684363 ]]]]



 [[[[0.73976536 0.28975147]
    [0.24716051 0.16085539]]

   [[0.9377152  0.2050373 ]
    [0.6956161  0.070695  ]]]


  [[[0.49439186 0.00610398]
    [0.14433113 0.22794225]]

   [[0.93030259 0.83946544]
    [0.88812634 0.64193697]]]]]
