In [1]:
import numpy as np

In [2]:
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [3]:
y  = x.reshape((3,2))
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [4]:
x = np.array([[1,2,3,4,5], [6,7,8,9,10]], dtype = np.uint8)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
y = np.reshape(x, 10)
print(y)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
y = np.ravel(x)
print(y)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
y = x.flatten()
print(y)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
y = x.flatten('F')
print(y)

[ 1  6  2  7  3  8  4  9  5 10]


In [12]:
y = x.flatten('C')
print(y)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
a = np.array([1,2,3,4,5], dtype = np.uint8)
b = np.array([6,7,8,9,10], dtype = np.uint8)

c = np.stack((a,b))
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
c = np.stack((a,b), axis = 0)
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
c = np.stack((a,b), axis = 1)
print(c)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [17]:
c = np.stack((a,b), axis = -1)
print(c)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [19]:
c = np.dstack((a,b))
print(c)

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


In [20]:
c = np.hstack((a,b))
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
c = np.vstack((a,b))
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
print(c.shape)

(2, 5)


In [23]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [24]:
a, b, c = np.split(x, 3)
print(a,b,c)

[0 1 2] [3 4 5] [6 7 8]


In [25]:
x = np.random.rand(4, 4, 4)
print(x)

[[[0.44605822 0.05710432 0.6903975  0.39174484]
  [0.13032406 0.98944501 0.40109351 0.45046871]
  [0.04074971 0.50788998 0.29368831 0.42745041]
  [0.84474027 0.78004838 0.44920844 0.03712461]]

 [[0.12398559 0.5977537  0.68336064 0.86505385]
  [0.0708991  0.19178895 0.16942915 0.3425129 ]
  [0.7113639  0.51836892 0.16023732 0.97445236]
  [0.17492761 0.30567887 0.45869867 0.30927496]]

 [[0.18369181 0.06190112 0.99953159 0.91031141]
  [0.46757798 0.01348197 0.56440106 0.16268891]
  [0.1135805  0.30725174 0.65161321 0.90323206]
  [0.41452703 0.36074514 0.85694094 0.69238777]]

 [[0.05312461 0.94118063 0.78226748 0.24296422]
  [0.20202016 0.17922522 0.68484641 0.21611511]
  [0.88939615 0.6454579  0.30626088 0.40698572]
  [0.54288771 0.98226325 0.38214022 0.36520111]]]


In [26]:
y, z = np.split(x, 2)
print(y, z)

[[[0.44605822 0.05710432 0.6903975  0.39174484]
  [0.13032406 0.98944501 0.40109351 0.45046871]
  [0.04074971 0.50788998 0.29368831 0.42745041]
  [0.84474027 0.78004838 0.44920844 0.03712461]]

 [[0.12398559 0.5977537  0.68336064 0.86505385]
  [0.0708991  0.19178895 0.16942915 0.3425129 ]
  [0.7113639  0.51836892 0.16023732 0.97445236]
  [0.17492761 0.30567887 0.45869867 0.30927496]]] [[[0.18369181 0.06190112 0.99953159 0.91031141]
  [0.46757798 0.01348197 0.56440106 0.16268891]
  [0.1135805  0.30725174 0.65161321 0.90323206]
  [0.41452703 0.36074514 0.85694094 0.69238777]]

 [[0.05312461 0.94118063 0.78226748 0.24296422]
  [0.20202016 0.17922522 0.68484641 0.21611511]
  [0.88939615 0.6454579  0.30626088 0.40698572]
  [0.54288771 0.98226325 0.38214022 0.36520111]]]


In [27]:
y, z = np.dsplit(x, 2)
print(y,z)

[[[0.44605822 0.05710432]
  [0.13032406 0.98944501]
  [0.04074971 0.50788998]
  [0.84474027 0.78004838]]

 [[0.12398559 0.5977537 ]
  [0.0708991  0.19178895]
  [0.7113639  0.51836892]
  [0.17492761 0.30567887]]

 [[0.18369181 0.06190112]
  [0.46757798 0.01348197]
  [0.1135805  0.30725174]
  [0.41452703 0.36074514]]

 [[0.05312461 0.94118063]
  [0.20202016 0.17922522]
  [0.88939615 0.6454579 ]
  [0.54288771 0.98226325]]] [[[0.6903975  0.39174484]
  [0.40109351 0.45046871]
  [0.29368831 0.42745041]
  [0.44920844 0.03712461]]

 [[0.68336064 0.86505385]
  [0.16942915 0.3425129 ]
  [0.16023732 0.97445236]
  [0.45869867 0.30927496]]

 [[0.99953159 0.91031141]
  [0.56440106 0.16268891]
  [0.65161321 0.90323206]
  [0.85694094 0.69238777]]

 [[0.78226748 0.24296422]
  [0.68484641 0.21611511]
  [0.30626088 0.40698572]
  [0.38214022 0.36520111]]]


In [29]:
y, z = np.hsplit(x, 2)
print(y, z)

[[[0.44605822 0.05710432 0.6903975  0.39174484]
  [0.13032406 0.98944501 0.40109351 0.45046871]]

 [[0.12398559 0.5977537  0.68336064 0.86505385]
  [0.0708991  0.19178895 0.16942915 0.3425129 ]]

 [[0.18369181 0.06190112 0.99953159 0.91031141]
  [0.46757798 0.01348197 0.56440106 0.16268891]]

 [[0.05312461 0.94118063 0.78226748 0.24296422]
  [0.20202016 0.17922522 0.68484641 0.21611511]]] [[[0.04074971 0.50788998 0.29368831 0.42745041]
  [0.84474027 0.78004838 0.44920844 0.03712461]]

 [[0.7113639  0.51836892 0.16023732 0.97445236]
  [0.17492761 0.30567887 0.45869867 0.30927496]]

 [[0.1135805  0.30725174 0.65161321 0.90323206]
  [0.41452703 0.36074514 0.85694094 0.69238777]]

 [[0.88939615 0.6454579  0.30626088 0.40698572]
  [0.54288771 0.98226325 0.38214022 0.36520111]]]


In [30]:
y, z = np.vsplit(x, 2)
print(y, z)

[[[0.44605822 0.05710432 0.6903975  0.39174484]
  [0.13032406 0.98944501 0.40109351 0.45046871]
  [0.04074971 0.50788998 0.29368831 0.42745041]
  [0.84474027 0.78004838 0.44920844 0.03712461]]

 [[0.12398559 0.5977537  0.68336064 0.86505385]
  [0.0708991  0.19178895 0.16942915 0.3425129 ]
  [0.7113639  0.51836892 0.16023732 0.97445236]
  [0.17492761 0.30567887 0.45869867 0.30927496]]] [[[0.18369181 0.06190112 0.99953159 0.91031141]
  [0.46757798 0.01348197 0.56440106 0.16268891]
  [0.1135805  0.30725174 0.65161321 0.90323206]
  [0.41452703 0.36074514 0.85694094 0.69238777]]

 [[0.05312461 0.94118063 0.78226748 0.24296422]
  [0.20202016 0.17922522 0.68484641 0.21611511]
  [0.88939615 0.6454579  0.30626088 0.40698572]
  [0.54288771 0.98226325 0.38214022 0.36520111]]]


In [32]:
x = np.arange(16).reshape(4, 4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [33]:
y = np.flip(x, axis = 0)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [35]:
y = np.flip(x, axis = -0)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [36]:
y = np.flip(x, axis = 1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [38]:
y = np.flip(x, axis = -1)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [40]:
y = np.fliplr(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [41]:
y = np.flipud(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [42]:
y = np.roll(x, 8)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [43]:
y = np.rot90(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]
