In [6]:
# Bitwise Operation
import numpy as np
x = np.array([1, 0, 1, 0], np.uint8)
y = np.array([0, 1, 0, 1], np.uint8)

print(np.bitwise_and(x, y))
print(np.bitwise_or(x, y))
print(np.bitwise_xor(x, y))
print(np.bitwise_not(x))

[0 0 0 0]
[1 1 1 1]
[1 1 1 1]
[254 255 254 255]
