In [1]:
# Statical Function

import numpy as np

a = np.random.randint(low = 0, high = 10, size = 10)
print(a)

[7 4 1 6 1 3 3 1 6 1]


In [2]:
print(np.mean(a))

3.3


In [3]:
print(np.median(a))

3.0


In [4]:
print(np.average(a))

3.3


In [5]:
print(np.std(a))

2.238302928559939


In [6]:
print(np.var(a))

5.01


In [7]:
print(np.histogram(a))

(array([4, 0, 0, 2, 0, 1, 0, 0, 2, 1]), array([1. , 1.6, 2.2, 2.8, 3.4, 4. , 4.6, 5.2, 5.8, 6.4, 7. ]))


In [10]:
x = np.empty([3,3], np.uint8)
print(x)

[[248 235   2]
 [215  10 127]
 [  0   0 248]]


In [11]:
print(np.mean(x))

120.55555555555556


In [12]:
print(np.median(x))

127.0


In [13]:
print(np.average(x))

120.55555555555556


In [14]:
print(np.std(x))

110.49797495490948


In [15]:
print(np.var(x))

12209.802469135802


In [16]:
print(np.histogram(x))

(array([4, 0, 0, 0, 0, 1, 0, 0, 1, 3]), array([  0. ,  24.8,  49.6,  74.4,  99.2, 124. , 148.8, 173.6, 198.4,
       223.2, 248. ]))
